"""Removed categories from Article, populating CategoryTag

Revision ID: a15be6b25763
Revises: ab400bb83afe
Create Date: 2022-11-10 17:17:14.218616

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a15be6b25763'
down_revision = 'ab400bb83afe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'categories')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass