"""Added categories, removed embeddings

Revision ID: df57a16cf7b9
Revises: a5ee903f602b
Create Date: 2022-11-09 13:02:48.317309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df57a16cf7b9'
down_revision = 'a5ee903f602b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('categories', sa.String(), nullable=True))
    op.drop_column('articles', 'abstract_embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('abstract_embedding', sa.BLOB(), nullable=True))
    op.drop_column('articles', 'categories')
    # ### end Alembic commands ###
