"""Relationships

Revision ID: ea147039dca6
Revises:
Create Date: 2022-08-30 14:02:58.500577

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ea147039dca6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("abstract", sa.String(), nullable=True),
        sa.Column("abstract_embedding", sa.BLOB(length=16777215), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("submitter", sa.String(), nullable=True),
        sa.Column("journal_ref", sa.String(), nullable=True),
        sa.Column("doi", sa.String(), nullable=True),
        sa.Column("authors", sa.String(), nullable=True),
        sa.Column("updated_at", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "category_tags",
        sa.Column("tag", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("tag"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "category_tags_articles",
        sa.Column("category_tag_id", sa.String(), nullable=False),
        sa.Column("article_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_tag_id"],
            ["category_tags.tag"],
        ),
        sa.PrimaryKeyConstraint("category_tag_id", "article_id"),
    )
    op.create_table(
        "user_article_preferences",
        sa.Column("article_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "sentiment", sa.Enum("like", "dislike", name="usersentiment"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("article_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_article_preferences")
    op.drop_table("category_tags_articles")
    op.drop_table("user")
    op.drop_table("category_tags")
    op.drop_table("articles")
    # ### end Alembic commands ###
